import { readFile } from "node:fs/promises";
import vm from "node:vm";
import { beforeAll, describe, expect, test } from "vitest";
let core; beforeAll(async () => { await import("./probe-core.js"); core = globalThis.QuotaBarProbeCore; });
const at = "2026-01-02T03:04:05.000Z";
const atB = "2026-01-03T03:04:05.000Z";
const endpoint = (probeSlot, planClass) => ({ version: "v1", probeSlot, planClass, source: "usage_endpoint", observedAt: at, windows: [{ kind: "five_hour", usedPercent: probeSlot === "profile-a" ? 25 : 45, resetAt: probeSlot === "profile-a" ? at : atB }, { kind: "weekly", usedPercent: probeSlot === "profile-a" ? 50 : 65, resetAt: probeSlot === "profile-a" ? at : atB }], status: "available" });
const sse = (probeSlot, planClass) => ({ version: "v1", probeSlot, planClass, source: "completion_sse", observedAt: at, windows: [{ kind: "five_hour", usedPercent: probeSlot === "profile-a" ? 10 : 20, resetAt: probeSlot === "profile-a" ? at : atB }], status: "available" });
const unavailableSse = (probeSlot, planClass) => ({ version: "v1", probeSlot, planClass, source: "completion_sse", observedAt: at, windows: [], status: "unavailable", errorCode: "unavailable" });
const overflowedSse = (probeSlot, planClass) => ({ version: "v1", probeSlot, planClass, source: "completion_sse", observedAt: at, windows: [], status: "malformed", errorCode: "overflow" });
const malformedSse = (probeSlot, planClass) => ({ version: "v1", probeSlot, planClass, source: "completion_sse", observedAt: at, windows: [], status: "malformed", errorCode: "malformed_payload" });
const paid = endpoint("profile-a", "paid"), free = sse("profile-b", "free");
function tracked(text, headers = { "content-type": "text/event-stream" }) { let cancelled = 0; const body = new ReadableStream({ start(c) { c.enqueue(new TextEncoder().encode(text)); }, cancel() { cancelled++; } }); return { response: new Response(body, { headers }), cancelled: () => cancelled }; }
async function shippedWorld(order) {
  const [contentSource, pageSource] = await Promise.all(["content.js", "page-observer.js"].map((file) => readFile(new URL(file, import.meta.url), "utf8")));
  let stored = {}, pending = [];
  const session = { get: async () => structuredClone(stored), set: async (value) => { stored = structuredClone(value); } }, handle = core.createSessionHandler(session), listeners = [], sent = [];
  const window = {
    addEventListener(type, listener) { if (type === "message") listeners.push(listener); },
    postMessage(data, origin) { for (const listener of [...listeners]) listener({ source: window, origin, data }); },
    fetch: (...args) => Promise.resolve(args[2]),
  };
  const chrome = { runtime: { sendMessage(message) { sent.push(message); pending.push(handle(message)); } } }, context = { window, location: { origin: "https://claude.ai" }, chrome, QuotaBarProbeCore: core };
  const run = (source) => vm.runInNewContext(source, context);
  if (order === "isolated-first") { run(contentSource); run(pageSource); } else { run(pageSource); run(contentSource); }
  const flush = async () => { for (let i = 0; i < 8; i++) { const batch = pending; pending = []; await Promise.all(batch); await new Promise((resolve) => setTimeout(resolve, 5)); } };
  await flush();
  return { window, sent, flush, state: async () => (await handle({ type: "get-state" })).state };
}

describe("shipped validator", () => {
  test("strict timestamps normalize valid offsets and reject invalid calendar/time values", () => { expect(core.normalizeRfc3339("2026-01-02T04:04:05+01:00")).toBe(at); for (const value of ["2026-02-30T03:04:05Z", "2026-01-02T24:00:00Z", "2026-01-02T03:60:00Z", "2026-01-02T03:04:60Z"]) expect(core.normalizeRfc3339(value)).toBeUndefined(); expect(core.unixSeconds(8.64e12 + 1)).toBeUndefined(); });
  test("rejects unknown and forbidden sentinel fields before serialization/errors", () => { for (const key of ["route", "organizationId", "email", "token", "cookie", "authorization", "conversation", "messageId", "requestId", "traceId", "headers", "body", "text"]) { const out = core.safeEnvelope({ ...paid, [key]: "FORBIDDEN-SENTINEL" }); expect(out).toBeNull(); expect(JSON.stringify(out)).not.toContain("FORBIDDEN-SENTINEL"); } expect(core.isSanitizedEnvelope({ ...paid, extra: true })).toBe(false); });
});

describe("shipped stream parsers", () => {
  test("endpoint streams under 32 KiB and handles absent, false, and oversized Content-Length", async () => { await expect(core.drainEndpoint(new Response(JSON.stringify({ five_hour: { utilization: 25, resets_at: at } })))).resolves.toMatchObject({ kind: "found" }); await expect(core.drainEndpoint(new Response("{}", { headers: { "content-length": "false" } }))).resolves.toEqual({ kind: "found", windows: [] }); await expect(core.drainEndpoint(new Response("{}", { headers: { "content-length": "32769" } }))).resolves.toEqual({ kind: "overflow" }); });
  test("cancels clone readers on endpoint overflow and SSE success/malformed/end", async () => { const e = tracked("x".repeat(core.MAX_ENDPOINT_BYTES + 1), { "content-type": "application/json" }); await core.drainEndpoint(e.response); expect(e.cancelled()).toBeGreaterThanOrEqual(1); for (const text of ['data: {"type":"message_limit","message_limit":{"windows":{"5h":{"utilization":.1}}}}\n', 'data: {"type":"message_limit"}\n']) { const s = tracked(text); await core.parseMessageLimitSse(s.response); expect(s.cancelled()).toBeGreaterThanOrEqual(1); } await expect(core.parseMessageLimitSse(new Response("data: ignored\n", { headers: { "content-type": "text/event-stream" } }))).resolves.toEqual({ kind: "none" }); });
  test("fails closed for huge SSE lines with or without newline and requires content type", async () => { for (const ending of ["", "\n"]) await expect(core.parseMessageLimitSse(new Response(`data: ${"x".repeat(core.MAX_SSE_LINE_BYTES + 1)}${ending}`, { headers: { "content-type": "text/event-stream" } }))).resolves.toEqual({ kind: "overflow" }); const good = 'data: {"type":"message_limit","message_limit":{"windows":{"5h":{"utilization":0.25,"resets_at":1767323045},"7d":{"utilization":0.5,"resets_at":1767409445}}}}\n'; await expect(core.parseMessageLimitSse(new Response(good))).resolves.toEqual({ kind: "malformed" }); await expect(core.parseMessageLimitSse(new Response(good, { headers: { "content-type": "text/event-stream; charset=utf-8" } }))).resolves.toMatchObject({ kind: "found" }); });
  test("selects only allowed windows from the documented message_limit shape with provider extras", async () => { const raw = { type: "message_limit", message_limit: { windows: { "5h": { utilization: 0.25, resets_at: 1767323045, surpassed_threshold: false }, "7d": { utilization: 0.5, resets_at: 1767409445, surpassed_threshold: false }, "7d_oi": { utilization: 0.9 }, overage: { enabled: true } }, plan_name: "FORBIDDEN-SENTINEL", unrelated: true } }; expect(core.selectSseWindows(raw)).toEqual([{ kind: "five_hour", usedPercent: 25, resetAt: at }, { kind: "weekly", usedPercent: 50, resetAt: "2026-01-03T03:04:05.000Z" }]); expect(core.selectSseWindows({ type: "message_limit", windows: {} })).toBeNull(); });
  test("does not interfere with original responses", async () => { const response = new Response("synthetic"); let seen = false; expect(core.observeWithoutInterference(response, async (clone) => { seen = await clone.text() === "synthetic"; })).toBe(response); await new Promise((r) => setTimeout(r)); expect(await response.text()).toBe("synthetic"); expect(seen).toBe(true); });
});

describe("routes and session state", () => {
  test("shipped installer normalizes URL inputs and enforces methods, origin, paths, and event streams", async () => { const calls = [], stages = [], target = { fetch: (...args) => Promise.resolve(args[2]) }, fake = (type) => ({ headers: { get: () => type }, clone: () => { calls.push("clone"); return {}; } }), undo = core.installFetchObserver(target, "https://claude.ai", async () => calls.push("usage"), async () => calls.push("sse"), (stage) => stages.push(stage)); await target.fetch("https://other.invalid/api/organizations/x/usage", { method: "GET" }, fake("application/json")); await target.fetch("/api/organizations/x/chat_conversations/y/completion", { method: "GET" }, fake("text/event-stream")); await target.fetch("/api/organizations/x/chat_conversations/y/completion", { method: "POST" }, fake("application/json")); await new Promise((r) => setTimeout(r)); expect(calls).toEqual([]); await target.fetch("/api/organizations/x/usage?ignored=1", { method: "GET" }, fake("application/json")); await target.fetch("https://claude.ai/api/organizations/x/chat_conversations/y/completion?ignored=1", { method: "POST" }, fake("text/event-stream")); await target.fetch(new Request("https://claude.ai/api/organizations/x/chat_conversations/y/completion?ignored=1", { method: "POST" }), undefined, fake("text/event-stream")); await target.fetch(new URL("https://claude.ai/api/organizations/x/chat_conversations/y/retry_completion?ignored=1"), { method: "POST" }, fake("text/event-stream")); await new Promise((r) => setTimeout(r)); expect(calls).toEqual(["clone", "usage", "clone", "sse", "clone", "sse", "clone", "sse"]); expect(stages.filter((stage) => stage === "completion_matched")).toHaveLength(4); expect(stages.filter((stage) => stage === "event_stream_recognized")).toHaveLength(3); undo(); });
  test("shipped session handler keeps quota and fixed diagnostics isolated through worker recreation", async () => { let stored = {}; const session = { get: async () => structuredClone(stored), set: async (value) => { stored = structuredClone(value); } }; let handle = core.createSessionHandler(session); for (const [slot, plan] of [["profile-a", "paid"], ["profile-b", "free"]]) { await handle({ type: "set-settings", slot, planClass: plan }); await handle({ type: "stage", stage: "bridge_loaded" }); await handle({ type: "stage", stage: "observer_installed" }); await handle({ type: "stage", stage: "bridge_received_main_ready" }); await handle({ type: "observation", output: endpoint(slot, plan) }); await handle({ type: "observation", output: unavailableSse(slot, plan) }); let state = (await handle({ type: "get-state" })).state; expect(state.observations[slot].source).toBe("usage_endpoint"); await handle({ type: "stage", stage: "completion_matched" }); await handle({ type: "stage", stage: "event_stream_recognized" }); await handle({ type: "stage", stage: "message_limit_found" }); await handle({ type: "observation", output: sse(slot, plan) }); state = (await handle({ type: "get-state" })).state; expect(state.observations[slot]).toEqual(sse(slot, plan)); expect(core.popupView(state)).toMatchObject({ buildId: core.BUILD_ID, slot, planClass: plan, diagnostic: "sanitized_observation_stored", observation: sse(slot, plan) }); await handle({ type: "stage", stage: "completion_parse_failed" }); await handle({ type: "observation", output: endpoint(slot, plan) }); await handle({ type: "observation", output: overflowedSse(slot, plan) }); await handle({ type: "observation", output: malformedSse(slot, plan) }); state = (await handle({ type: "get-state" })).state; expect(state.observations[slot]).toEqual(sse(slot, plan)); expect(state.diagnostics[slot]).toBe("completion_parse_failed"); await handle({ type: "stage", stage: "completion_seen_no_message_limit" }); state = (await handle({ type: "get-state" })).state; expect(state.diagnostics[slot]).toBe("completion_seen_no_message_limit"); }
    handle = core.createSessionHandler(session); await handle({ type: "set-settings", slot: "profile-a", planClass: "paid" }); const state = (await handle({ type: "get-state" })).state; expect(state.observations["profile-a"]).toEqual(sse("profile-a", "paid")); expect(state.observations["profile-b"]).toEqual(sse("profile-b", "free")); });
  test("actual shipped MAIN and ISOLATED handlers reach readiness in both registration orders", async () => { for (const order of ["isolated-first", "main-first"]) { const world = await shippedWorld(order), state = await world.state(), stages = world.sent.filter((message) => message.type === "stage").map((message) => message.stage); expect(stages).toContain("bridge_loaded"); expect(stages).toContain("observer_installed"); expect(stages).toContain("bridge_received_main_ready"); expect(state.diagnostics["profile-a"]).toBe("bridge_received_main_ready"); } });
  test("actual shipped SSE handlers emit truthful stages and preserve an available observation", async () => { const found = 'data: {"type":"message_limit","message_limit":{"windows":{"5h":{"utilization":0.25,"resets_at":1767323045}}}}\n', malformed = 'data: {"type":"message_limit"}\n', overflow = `data: ${"x".repeat(core.MAX_SSE_LINE_BYTES + 1)}\n`; const world = await shippedWorld("isolated-first"), stages = () => world.sent.filter((message) => message.type === "stage").map((message) => message.stage), response = (text) => ({ headers: { get: () => "text/event-stream" }, clone: () => new Response(text, { headers: { "content-type": "text/event-stream" } }) }); await world.window.fetch("https://claude.ai/api/organizations/x/chat_conversations/y/completion", { method: "POST" }, response(found)); await world.flush(); let state = await world.state(); expect(world.sent).toContainEqual(expect.objectContaining({ type: "observation" })); expect(stages()).toEqual(expect.arrayContaining(["completion_matched", "event_stream_recognized", "message_limit_found"])); expect(state.observations["profile-a"].source).toBe("completion_sse"); const firstStageCount = stages().length; await world.window.fetch("/api/organizations/x/chat_conversations/y/completion", { method: "POST" }, response("data: ignored\n")); await world.flush(); state = await world.state(); expect(stages().slice(firstStageCount)).toEqual(expect.arrayContaining(["completion_matched", "event_stream_recognized", "completion_seen_no_message_limit"])); expect(state.observations["profile-a"].source).toBe("completion_sse"); for (const text of [malformed, overflow]) { const before = stages().length; await world.window.fetch("/api/organizations/x/chat_conversations/y/retry_completion", { method: "POST" }, response(text)); await world.flush(); state = await world.state(); const emitted = stages().slice(before); expect(emitted).toEqual(expect.arrayContaining(["completion_matched", "event_stream_recognized", "completion_parse_failed"])); expect(emitted).not.toContain("message_limit_found"); expect(state.observations["profile-a"].source).toBe("completion_sse"); expect(state.diagnostics["profile-a"]).toBe("completion_parse_failed"); } });
  test("fixed postMessage contract rejects wrong source, origin, type, and fields", () => { const target = {}, origin = "https://claude.ai", request = { type: "quotabar-local-probe-ready-request", buildId: core.BUILD_ID }, ready = { type: "quotabar-local-probe-main-ready", buildId: core.BUILD_ID }, stage = { type: "quotabar-local-probe-stage", buildId: core.BUILD_ID, stage: "observer_installed" }; expect(core.validWindowMessage({ source: target, origin, data: request }, target, origin)).toEqual(request); expect(core.validWindowMessage({ source: target, origin, data: ready }, target, origin)).toEqual(ready); expect(core.validWindowMessage({ source: target, origin, data: stage }, target, origin)).toEqual(stage); for (const event of [{ source: {}, origin, data: ready }, { source: target, origin: "https://other.invalid", data: ready }, { source: target, origin, data: { ...ready, extra: true } }, { source: target, origin, data: { type: "wrong", buildId: core.BUILD_ID } }]) expect(core.validWindowMessage(event, target, origin)).toBeUndefined(); });
});

test("manifest, popup dependency order, and shipped-source capability scans stay local-only", async () => { const m = (await import("./manifest.json", { with: { type: "json" } })).default, fs = await import("node:fs/promises"); expect(m.permissions).toEqual(["storage"]); expect(m.host_permissions).toEqual(["https://claude.ai/*"]); expect(m.web_accessible_resources).toBeUndefined(); expect(m.content_scripts[0].js).toEqual(["probe-core.js", "content.js"]); expect(m.content_scripts[1].js).toEqual(["probe-core.js", "page-observer.js"]); const source = await Promise.all(["background.js", "content.js", "page-observer.js", "popup.js", "probe-core.js"].map((file) => fs.readFile(new URL(file, import.meta.url), "utf8"))), html = await fs.readFile(new URL("popup.html", import.meta.url), "utf8"); expect(html.indexOf('src="probe-core.js"')).toBeGreaterThanOrEqual(0); expect(html.indexOf('src="probe-core.js"')).toBeLessThan(html.indexOf('src="popup.js"')); for (const forbidden of ["storage.local", "console.", "nativeMessaging", "localhost", "XMLHttpRequest", "WebSocket", "FORBIDDEN-SENTINEL"]) expect(source.join("\n")).not.toContain(forbidden); });
